// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAqmEUaU8rMIun3Pu5p0-1ilN9PaJbBHU',
    appId: '1:311617274959:web:2a81e1b753043c63b0163a',
    messagingSenderId: '311617274959',
    projectId: 'oneamov-app',
    authDomain: 'oneamov-app.firebaseapp.com',
    storageBucket: 'oneamov-app.appspot.com',
    measurementId: 'G-WYEQ9WQ1Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOKZZoBk2ilrwoYUcb-Ic43NQpf-b9zSM',
    appId: '1:311617274959:android:5e38b84a9ef36218b0163a',
    messagingSenderId: '311617274959',
    projectId: 'oneamov-app',
    storageBucket: 'oneamov-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2sUedIRKWFNZamnoiPCL9EXqdyDR6APk',
    appId: '1:311617274959:ios:70accb3f80762b39b0163a',
    messagingSenderId: '311617274959',
    projectId: 'oneamov-app',
    storageBucket: 'oneamov-app.appspot.com',
    iosBundleId: 'com.example.oneamov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2sUedIRKWFNZamnoiPCL9EXqdyDR6APk',
    appId: '1:311617274959:ios:70accb3f80762b39b0163a',
    messagingSenderId: '311617274959',
    projectId: 'oneamov-app',
    storageBucket: 'oneamov-app.appspot.com',
    iosBundleId: 'com.example.oneamov',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAqmEUaU8rMIun3Pu5p0-1ilN9PaJbBHU',
    appId: '1:311617274959:web:827137b3d1e44df1b0163a',
    messagingSenderId: '311617274959',
    projectId: 'oneamov-app',
    authDomain: 'oneamov-app.firebaseapp.com',
    storageBucket: 'oneamov-app.appspot.com',
    measurementId: 'G-Z0KR8V8Y17',
  );
}
